config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#index'
  get 'character' => 'characters#show', as: 'character'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  def show
    request = HTTParty.get(params[:id], query: {format: 'json'})
    @character = CharacterSerializer.new
    if request.success?
      @character.from_json(request.body)
    end
  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/characters/show.html.haml
.row-content
  - if @character.name.present?
    %h1.text-center.card-title= @character.name
    .card-deck
      .card
        .card-body
          %h4.text-center.card-title Information
          %p
            %b Gender:
            = @character.gender
            %br
            %b Birth Year:
            = @character.birth_year
            %br
            %b Home World:
            = @character._homeworld
      .card
        .card-body
          %h4.text-center.card-title Vehicles
        %u.list-group.list-group-flush
          - @character.vehicles_list.each do |vehicle|
            %li.list-group-item= vehicle.name
  - else
    %h1.text-center.card-title Character not Found

.row-content.text-center
  %br
  %br
  = link_to "Back", root_path, class: 'btn btn-dark'

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 4.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}", :role  => "alert"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Star Wars App'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Star Wars App'}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload'
    = stylesheet_link_tag 'https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css', media: 'all'
    = csrf_meta_tags

  %body
    %header
    %main{:role => "main"}
      = render 'layouts/messages'
      = link_to root_path do
        .row.justify-content-md-center
          .col-md-4
            = image_tag 'star_wars.png', class: 'star-logo'
          .col-md-4.text-right
            = image_tag 'death_star_icon.png', class: 'death-logo'

      = yield

  = javascript_include_tag 'application', 'data-turbolinks-track' => 'reload'

app/views/visitors/index.html.erb
.row-content.text-center
  = form_tag character_path, method: :get do
    = select_tag "id", nil, class: 'select-sw-character'

app/views/visitors/index.html.haml
.row-content.text-center
  = form_tag character_path, method: :get do
    = select_tag "id", nil, class: 'select-sw-character'